
connectfour: system execution failed.
Following is the set of recorded exceptions:

******************************** Thread exception *****************************
In thread           Root thread            0x0 (thread id)
*******************************************************************************
-------------------------------------------------------------------------------
Class / Object      Routine                Nature of exception           Effect
-------------------------------------------------------------------------------
ARRAY2              item @1                valid_row:                   
<0000000004234E48>                         Precondition violated.        Fail
-------------------------------------------------------------------------------
BOARD               right_diagonal_check @5
<0000000004234E28>                         Routine failure.              Fail
-------------------------------------------------------------------------------
APPLICATION         make @25                                            
<00000000042345A8>                         Routine failure.              Fail
-------------------------------------------------------------------------------
APPLICATION         root's creation                                     
<00000000042345A8>                         Routine failure.              Exit
-------------------------------------------------------------------------------
